### ISSUE TITLE
Discuss swag design - swarm designs for shirts/hoodies

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/media#13]

**Comment by paulespino** [comment]
Hi! @mrmetaverse  Whats the scope for this? I can help :)

**Comment by mrmetaverse** [comment]
> Hi! @mrmetaverse  Whats the scope for this? I can help :)

Hey @paulespino, thanks for reaching out. This is a new item, and maybe @LightLodges can give some more context. We would love for our community to create designs for merch. 

I have already set up a store for now using a super convenient tool called teespring.
