### ISSUE TITLE
Define Media and Content Strategy Roadmap

### ISSUE THREAD

**Issue by pcsmgnt** [omigroup/media#20]
I would like to propose a step before the content sprint. I think we should define and share with the community what good looks like for the Media and Content strategy WG. The roadmap should comprise the end-state, but more importantly, the early stage model (based on where we are). I feel the following will lay a good foundation for securing buy-in from the community and allow time for design automation to ensure future content sprints. 

- Start with an assessment of current channels and assess efficacy (looking at the PPTI elements involved). I assume there are limited resources. Are we ready to drop channels that are not giving the traction we would like to see? What traction would we like to see. We should define performance metrics. Those will be useful for the dashboard proposed. https://github.com/omigroup/media/issues/22 **(done)**  Notes and next steps: https://docs.google.com/spreadsheets/d/1dxKlE2tVTz4zbQ-BRZh5tRoP5Lmgsy0KOY1o6htD5aY/edit?usp=sharing
- Set clear objectives for the short, medium and long term https://github.com/omigroup/media/issues/23
- Prioritise the channels that make the most sense and define scope https://github.com/omigroup/media/issues/24
- Design a two track process that accommodates scheduled and adhoc content submissions, reviews, posting and engagement https://github.com/omigroup/media/issues/25
- Share the straw-man with the community and invite feedback for consideration https://github.com/omigroup/media/issues/26
- Build, test and disseminate the process, tools and explainer videos to the community https://github.com/omigroup/media/issues/27 https://github.com/omigroup/media/issues/28
- Hold an AMA to address questions/queries/suggestions from the community https://github.com/omigroup/media/issues/29
- Run the process (testing it with the proposed content https://github.com/omigroup/media/issues/30 sprint https://github.com/omigroup/media/issues/3)

**Comment by pcsmgnt** [comment]
I have completed the following:

-  Created official links channel for official media links in Discord
- Embedded links using Mee6 bot to complete some actions listed below
- Created Discord channel for internal comms and explainer videos
- Posted socials for easy access and reference
- Submitted content to airtable incl. Metavere article

Pending Action
* Post "How to become and contributor" explainer video (Anthony) TBC

These were part of the blocked actions

**Comment by mrmetaverse** [comment]
bump, media team want to do this still? Or was this done? Or should we move to archive? :)

**Comment by pcsmgnt** [comment]
Hey! Makes sense to close as this was put together before the suggestion to separate the innovation and automation track (periodic) from the business-as-usual function of creating and curating content. I support th emotion to close this.

**Comment by pcsmgnt** [comment]
I mean I can close too
