### ISSUE TITLE
content sprint

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/media#3]
Conduct our first content stategy sprint

**Comment by LightLodges** [comment]
In omi-media channel on discord we're tracking topics/work ahead include CURATION (blog posts coming from all of you to go to website team & social media), creating for SOCIAL CHANNELS (youtube, twitter, twitch etc), PUBLISHING CALENDAR and the related EVENTS scheduling (digital + physical until those have their own group to manage). Our goal is to meet monthly to go deep through content strategy and plan posts together, scheduling and automating the elements we receive from all of you. We're testing content management solutions that can help us aggregate & coordinate/plan publishing needs including sanity.io and we will need support from 1) occasional blog post contributors 2) video creators/streamers 3) occasional channel maintainers & 4) people who want to publish together with OMI for the monthly content media mtgs along with 5) event co-producers and hosts. Content calendar will be synced to our events + interoperability working group focus points, so if you're leading another working group expect we'll be in touch to organize how we can publish easier guides to your work together and WHEN you'd like to prep for publishing together (interviews, blog posts, demos, etc).

We want to nail down an extended work session for content wrangling in May with an automated workflow TBD (assessing tools now).

For anyone else who is currently publishing within the OMI community - blog posts, social posts, videos and other content you'd like to make available to OMI to reshare/repost for the website or social channels, you can send those to us anytime here: https://airtable.com/shrZAsV1MA5QJctYx  (thanks @Shadow for your help on this). We'll get this on the readme as well for future media contributions until we settle on a full automated content management workflow or platform to streamline all submissions.

**Comment by mrmetaverse** [comment]
archive
