### ISSUE TITLE
Video: how to contribute to our blog

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/media#36]
Anthony @antpb and Evo @LightLodges to do a step by step video of the back end of WordPress to demonstrate how members of OMI can become contributors. 

Video will be posted on YouTube and Twitter.

**Comment by LightLodges** [comment]
Wednesday in Streamyard via screenshare to our YouTube and other channels, we'll need to make sure to make that video easy to find here and there after we go live

**Comment by mrmetaverse** [comment]
Ok great! Can we create a discord event for the time that works for you two?

**Comment by mrmetaverse** [comment]
bump
