### ISSUE TITLE
Twitter post bot

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/media#40]
Twitter post bot

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/239#discussioncomment-2865560_

**Comment by pcsmgnt** [comment]
@mrmetaverse 🛑 ✋🏽**Blocked!** I have tried over the last 24 hours to login to the Twitter account with no luck. I even tried with 1Password. I need someone with access to login and grant the api access.

**_Steps Required_**
1. Navigate to this link: https://api.twitter.com/oauth/authorize?oauth_token=R9XLWQAAAAABEkY3AAABgT5g1A4
2. Login and grant access to the api.
3. Let me know when steps complete and I will complete the configuration on my side.

Thank you!

**Comment by mrmetaverse** [comment]
@pcsmgnt I can help now for 10 min?

**Comment by mrmetaverse** [comment]
![image](https://user-images.githubusercontent.com/63426722/172677424-ee495727-e04b-416f-aafe-e6328c3df4f0.png)
