### ISSUE TITLE
2022-07-12 WG Updates

### ISSUE THREAD

**Issue by pcsmgnt** [omigroup/media#44]
Evo and I met for this month's Media and Content WG. Outcomes below:
1. Evo added to TweetShift
2. Evo and I tested co-tweeting with success. It is something the community can explore for spreading the word. We don't have it yet in the UK #FYI 
3. @mrmetaverse  We need to allow the team to connect/login to our accounts before the 27th. Evo and I need time with you to resolve the login issues via 1Password if that is the solution of choice. Currently blocked on a few items. Please let us know when would be best to meet.

**Comment by mrmetaverse** [comment]
Ok thanks @pcsmgnt, I have some time tomorrow - Friday, grab any slot that works here: https://savvycal.com/mrmetaverse/chat

**Comment by pcsmgnt** [comment]
Evo, I suggest you go ahead and meet with Jesse @mrmetaverse  tomorrow. Tomorrow is one of my busiest days. I will probably only be able to schedule time later in the week on Friday or next week and I do not want to be a bottleneck on this.
