### ISSUE TITLE
Explore forming a Streaming Team

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/media#45]
Form a small group to create a process for recording and streaming various types of sessions and events. Recording weekly meetings, working group sessions, Demo Nights, etc. 

We are currently using OBS and StreamYard pro, Evo can expand StreamYard Pro to a team but we need a plan in place and people identified to give those roles.

**Comment by mrmetaverse** [comment]
bump, this was brought back up today during refinement

**Comment by mrmetaverse** [comment]
@LightLodges has more bandwidth for this sort of effort

**Comment by mrmetaverse** [comment]
Do we still want a streaming team?

**Comment by mrmetaverse** [comment]
What does this look like? Do we have interest for this effort? For example, I may enjoy being a speaker or guest on a stream but would need to know more about the time requirements, etc. 

Can you submit a working group proposal using the issue template?

**Comment by pcsmgnt** [comment]
A few new comers have expressed an interest to assist on the streaming side, including A. and a kind gentleman who offered to assist @LightLodges with editing video content. @LightLodges do you remember his name?
