### ISSUE TITLE
2022-08-13 WG Updates

### ISSUE THREAD

**Issue by pcsmgnt** [omigroup/media#49]
Another fruitful Content & Media WG Meeting!!

**_Discussed_**
- General: We have great ideas, but execution remains a challenge due to bandwidth. Recommendation to implement bounty board as a way on incentivising talent to help deliver some of our goals. See task #46 

- MSF: The role of the Media WG can control the narrative around the role of OMI as an SDO within MSF. This ties into an existing task on the MSF-Delegates repo. See task #47 

- Social Media Automation
-- We can scale the Twitter automation tool to Youtube content by reposting it to Twitter and using the trigger hashtags
-- Streamyard content can also be utilised in the same way by using the hashtags
-- We have a great tool that we should use to help promote the great work we are doing here as well as our achievements. People should be prompted to tweet out the meetings and engage with shared posts. It is a good way to work with the algorithms to help get the word out there. See task #48

- Optimise visibility and discoverability
-- Streaming OMI events live to Youtube by A. See Action #50
-- YouTube playlists to  (on-going work w/ @LightLodges)  
-- Phaneedra has offered to help edit long form video into snippets we can report on social media and has also agree to work with @LightLodges to repurposes videos from the demo into highlight content. See Action #51
-- The use of evergreen webinars as a steady sources of inbound traffic for the community. Can we edit a video using snippets from demo say to place on such platforms and have people engage with a CTA that brings them into the community? See Action #52
-- HackMD top-level link sharing the numerous projects and experiences in one place. The long term view would be to build out a 3D website that houses this for users to browse. In the mean time. Jin has shared HackMD high-level link (https://hackmd.io/@XR/neon-buidl/). Create Discord called omi-media-experiences for people to discover these assets for any PR/Media and share the link. See Action #53.
-- Utilising artefacts to promote our collective work, @LightLodges has provided assets made in midjourney that the community can utilise for media/promo. I will create a media assest channel that references the assets of github for easy referencing. See Actions #54 and #55

- Resourcing
-- Identifying builders of 3D websites. dework would be a great resource.
-- Setting up an OMI Group dework environment to allow members of the OMI community to share gigs and connect with talent. This could be a great source o new traffic for the community in terms of talent identification. Jin will experiment with the Content and Media WG repo and needs access rights granted @mrmetaverse please assist. (See Action #56)

- AOB
--Next Meeting is Tuesday 11th October at 16:00pm UTC (30 minutes later to accommodate MSF commitments). See Action #57
--Add #omiweeklytownhall and #omithw to tweetshift. See Action #58

**Comment by mrmetaverse** [comment]
THANK YOU so much @pcsmgnt 

Let's convert this to a discussion so it doesn't get lost in the "closed issues" section.

**Comment by pcsmgnt** [comment]
If only I knew how
