### ISSUE TITLE
Where to keep mee6 recordings as backup? git does not accept mpg files

### ISSUE THREAD

**Issue by indiebio** [omigroup/media#91]

**Comment by jimmy6DOF** [comment]
we also need to keep the transcripts also for RAG type ingesting (embedding for Avatar search-bot integration etc)

[OMI_wk153_0240417_Transcript_Diarized.json](https://github.com/omigroup/media/files/15178985/OMI_wk153_0240417_Transcript_Diarized.json)
[OMI_wk153_0240417_Transcript_Diarized.txt](https://github.com/omigroup/media/files/15178988/OMI_wk153_0240417_Transcript_Diarized.txt)

**Comment by indiebio** [comment]
Awesome! Argh that the recording stopped for some reason after 15 minutes. So these can be hosted on github, right, from both a technical storage (accepted file type, and size) perspective, and a privacy (not the raw file) perspective, correct? We would probably want a dedicated space for this, all nicely listed.

**Comment by indiebio** [comment]
@jin uses https://github.com/omigroup/recordings
